### ISSUE TITLE
tidy is not working on some version of linux

### ISSUE THREAD

**Issue by scherler** [vavere/htmltidy#17]
I am developing an app on my 

    Linux 3.2.0-56-generic #86-Ubuntu SMP Wed Oct 23 09:20:45 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
    Distributor ID:	Ubuntu
    Description:	Ubuntu 12.04.3 LTS
    Release:	12.04
    Codename:	precise

However on our pre-production machine tidy is not working correctly.

    Linux 3.5.0-42-generic #65~precise1-Ubuntu SMP Wed Oct 2 20:57:18 UTC 2013 x86_64 
    Distributor ID:	Ubuntu
    Description:	Ubuntu 12.04.2 LTS
    Release:	12.04
    Codename:	precise

When I use do 

    node_modules/htmltidy/bin/linux/tidy 

on my dev box is works as expected and doing the same on the other box leads to 

     -bash: node_modules/htmltidy/bin/linux/tidy: No such file or directory

However that file exists 

    cd node_modules/htmltidy/bin/linux/
    -rwxr-xr-x 1 owner codebusters 356632 Feb 23  2013 tidy

I ended up to install tidy by hand and then link it myself

    sudo apt-get install tidy -y
    ln -s /usr/bin/tidy /.../node_modules/htmltidy/bin/linux/

which fixes the problem, however I am not very keen to repeat it in production.

**Comment by dsifford** [comment]
Digging this up from the grave in case someone else comes across this in the future: 

I can confirm that [htmltidy2](https://github.com/c0b41/htmltidy2) fixes this error on Arch-based distros. :+1: 

...carry on.
